# Generated by Django 4.2.3 on 2023-08-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_raiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='raiting',
            new_name='rating',
        ),
    ]
